keys: &keys
  secret_key_base: 7ca8e9f89a73e9fc3554655af1b3f1646cf5dc7d5206c8bfbc264f6263c574c6d8f6439ec5b81a6ea94c7d6e55adc4f77bede492134233681416ffb98c77dda9
  bamboo_api_key:

development:
  <<: *keys

test:
  <<: *keys

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  bamboo_api_key: <%= ENV["BAMBOO_API_KEY"] %>
